version: "3.5"
services:
    mysql:
      image: mysql:8.0
      container_name: payouts-mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=payouts
        - MYSQL_DATABASE=payouts
        - MYSQL_USER=payouts
        - MYSQL_PASSWORD=payouts
      ports:
        - "8002:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      networks:
        - payouts_network
    webserver:
      image: nginx:alpine
      container_name: payouts-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"
      networks:
        - payouts_network
    php-fpm:
      build: docker/php-fpm
      container_name: payouts-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      networks:
        - payouts_network

networks:
  payouts_network:
    name: payouts_network
    ipam:
      config:
        - subnet: 172.66.0.0/24
